/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Marvel;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author georg
 */
public class IronManscreen extends javax.swing.JFrame {

    private ImageIcon images;
    private Icon icons;
    public IronManscreen() {
        initComponents();
        changeImage();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ironman = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ironman.setBackground(new java.awt.Color(255, 255, 255));

        history.setBackground(new java.awt.Color(255, 255, 255));
        history.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history.setOpaque(true);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(204, 0, 0));
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ironman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ironman, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(history, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        SHscreen.hero ="";
        Vscreen.villain="";
        SHscreen screen =new SHscreen();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IronManscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IronManscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IronManscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IronManscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IronManscreen().setVisible(true);
            }
        });
    }
    public void changeImage(){
    if(SHscreen.hero=="H1"){
        this.printImage(ironman,  "src/main/java/Images/h1fondo.jpg");
        history.setText("Y YO...,SOY IRON-MAN");
    }
    if(SHscreen.hero=="H2"){
        this.printImage(ironman,  "src/main/java/Images/h2fondo.gif");
        history.setText("HARIA ESTO TODO EL DIA");
    }
    if(SHscreen.hero=="H3"){
        this.printImage(ironman,  "src/main/java/Images/h3fondo.jpg");
        history.setText("TE DIJE QUE PAGARIAS POR ESO");
    }
    if(SHscreen.hero=="H4"){
        this.printImage(ironman,  "src/main/java/Images/h4fondo.jpg");
        history.setText("HULK APLASTA!!!");
    }
    if(SHscreen.hero=="H5"){
        this.printImage(ironman,  "src/main/java/Images/h5fondo.jpg");
        history.setText("NO NECESITAS DECIRME QUIEN SOY...");
    }
    if(SHscreen.hero=="H6"){
        this.printImage(ironman,  "src/main/java/Images/h6fondo.jpg");
        history.setText("NO HE VENIDO PARA NEGOCIAR");
    }
    if(SHscreen.hero=="H7"){
        this.printImage(ironman,  "src/main/java/Images/h7fondo.jpg");
        history.setText("NO TENGO NADA QUE DEMOSTRATE");
    }
    }
    private void printImage(JLabel lbs,String location){
        this.images = new ImageIcon(location);
        this.icons = new ImageIcon
        (this.images.getImage().getScaledInstance
                (lbs.getWidth(), 
                lbs.getHeight(),
                Image.SCALE_DEFAULT)
        );
        lbs.setIcon(this.icons);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel history;
    private javax.swing.JLabel ironman;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
