/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Marvel;
import Marvel.SHscreen;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author georg
 */
public class Proof extends javax.swing.JFrame {
    private ImageIcon images;
    private Icon icons;
    private int i =1;
    private int scoreH=0;
    private int scoreV=0;
    
    public Proof() {
        initComponents();
        this.setLocationRelativeTo(null);
        changelabel();
        this.printImage(this.imgPower,"src/main/java/Images/POWER.png");
        this.printImage(this.imgSpace,"src/main/java/Images/SPACE.png");
        this.printImage(this.imgReal,"src/main/java/Images/REAL.png");
        this.printImage(this.imgSoul,"src/main/java/Images/SOUL.png");
        this.printImage(this.imgTime,"src/main/java/Images/TIME.png");
        this.printImage(this.imgMind,"src/main/java/Images/MIND.png");
        scoreHero.setText("0");
        scoreVillain.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImgHero = new javax.swing.JLabel();
        imgVillain = new javax.swing.JLabel();
        attack1 = new javax.swing.JLabel();
        attack2 = new javax.swing.JLabel();
        attack3 = new javax.swing.JLabel();
        attack4 = new javax.swing.JLabel();
        attack5 = new javax.swing.JLabel();
        imgSpace = new javax.swing.JLabel();
        imgPower = new javax.swing.JLabel();
        imgReal = new javax.swing.JLabel();
        imgSoul = new javax.swing.JLabel();
        imgTime = new javax.swing.JLabel();
        imgMind = new javax.swing.JLabel();
        PjPower = new javax.swing.JLabel();
        PjSpace = new javax.swing.JLabel();
        PjReal = new javax.swing.JLabel();
        PjSoul = new javax.swing.JLabel();
        pjTime = new javax.swing.JLabel();
        pjMind = new javax.swing.JLabel();
        titleHero = new javax.swing.JLabel();
        titleVillain = new javax.swing.JLabel();
        labelVs = new javax.swing.JLabel();
        scoreHero = new javax.swing.JLabel();
        scoreVillain = new javax.swing.JLabel();
        guion = new javax.swing.JLabel();
        AttackB = new javax.swing.JButton();
        WinorLost = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lastAH = new javax.swing.JLabel();
        lastAV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        ImgHero.setBackground(new java.awt.Color(255, 255, 255));
        ImgHero.setOpaque(true);

        imgVillain.setBackground(new java.awt.Color(255, 255, 255));
        imgVillain.setOpaque(true);

        attack1.setBackground(new java.awt.Color(204, 0, 0));
        attack1.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        attack1.setForeground(new java.awt.Color(255, 255, 255));
        attack1.setOpaque(true);

        attack2.setBackground(new java.awt.Color(204, 0, 0));
        attack2.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        attack2.setForeground(new java.awt.Color(255, 255, 255));
        attack2.setOpaque(true);

        attack3.setBackground(new java.awt.Color(204, 0, 0));
        attack3.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        attack3.setForeground(new java.awt.Color(255, 255, 255));
        attack3.setOpaque(true);

        attack4.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        attack4.setForeground(new java.awt.Color(255, 255, 255));

        attack5.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        attack5.setForeground(new java.awt.Color(255, 255, 255));

        imgSpace.setBackground(new java.awt.Color(204, 0, 0));
        imgSpace.setOpaque(true);

        imgPower.setBackground(new java.awt.Color(204, 0, 0));
        imgPower.setOpaque(true);

        imgReal.setBackground(new java.awt.Color(204, 0, 0));
        imgReal.setOpaque(true);

        imgSoul.setBackground(new java.awt.Color(204, 0, 0));
        imgSoul.setOpaque(true);

        imgTime.setBackground(new java.awt.Color(204, 0, 0));
        imgTime.setOpaque(true);

        imgMind.setBackground(new java.awt.Color(204, 0, 0));
        imgMind.setOpaque(true);

        PjPower.setBackground(new java.awt.Color(204, 0, 0));
        PjPower.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        PjPower.setForeground(new java.awt.Color(255, 255, 255));
        PjPower.setOpaque(true);

        PjSpace.setBackground(new java.awt.Color(204, 0, 0));
        PjSpace.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        PjSpace.setForeground(new java.awt.Color(255, 255, 255));
        PjSpace.setOpaque(true);

        PjReal.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        PjReal.setForeground(new java.awt.Color(255, 255, 255));

        PjSoul.setBackground(new java.awt.Color(204, 0, 0));
        PjSoul.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        PjSoul.setForeground(new java.awt.Color(255, 255, 255));

        pjTime.setBackground(new java.awt.Color(204, 0, 0));
        pjTime.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        pjTime.setForeground(new java.awt.Color(255, 255, 255));
        pjTime.setOpaque(true);

        pjMind.setBackground(new java.awt.Color(204, 0, 0));
        pjMind.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        pjMind.setForeground(new java.awt.Color(255, 255, 255));
        pjMind.setOpaque(true);

        titleHero.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        titleHero.setForeground(new java.awt.Color(255, 255, 255));

        titleVillain.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        titleVillain.setForeground(new java.awt.Color(255, 255, 255));

        labelVs.setFont(new java.awt.Font("Burbank Big Condensed", 1, 48)); // NOI18N
        labelVs.setForeground(new java.awt.Color(255, 255, 255));
        labelVs.setText("VS");

        scoreHero.setBackground(new java.awt.Color(204, 0, 0));
        scoreHero.setFont(new java.awt.Font("Burbank Big Condensed", 1, 48)); // NOI18N
        scoreHero.setForeground(new java.awt.Color(255, 255, 255));
        scoreHero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreHero.setOpaque(true);

        scoreVillain.setBackground(new java.awt.Color(204, 0, 0));
        scoreVillain.setFont(new java.awt.Font("Burbank Big Condensed", 1, 48)); // NOI18N
        scoreVillain.setForeground(new java.awt.Color(255, 255, 255));
        scoreVillain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreVillain.setOpaque(true);

        guion.setBackground(new java.awt.Color(204, 0, 0));
        guion.setFont(new java.awt.Font("Burbank Big Condensed", 1, 48)); // NOI18N
        guion.setForeground(new java.awt.Color(255, 255, 255));
        guion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guion.setText("-");
        guion.setOpaque(true);

        AttackB.setBackground(new java.awt.Color(255, 153, 0));
        AttackB.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        AttackB.setForeground(new java.awt.Color(204, 0, 0));
        AttackB.setText("ATTACK");
        AttackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackBActionPerformed(evt);
            }
        });

        WinorLost.setBackground(new java.awt.Color(204, 0, 0));
        WinorLost.setFont(new java.awt.Font("Burbank Big Condensed", 1, 36)); // NOI18N
        WinorLost.setForeground(new java.awt.Color(255, 255, 255));
        WinorLost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinorLost.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lastAH.setBackground(new java.awt.Color(204, 0, 0));
        lastAH.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        lastAH.setForeground(new java.awt.Color(255, 255, 255));
        lastAH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastAH.setOpaque(true);

        lastAV.setBackground(new java.awt.Color(204, 0, 0));
        lastAV.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        lastAV.setForeground(new java.awt.Color(255, 255, 255));
        lastAV.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(attack4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(109, 109, 109))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(attack3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton1)
                                .addGap(114, 114, 114))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(attack5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imgTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(pjTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imgMind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(PjPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(imgSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PjSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pjMind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgReal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PjReal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(imgSoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PjSoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titleHero, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(labelVs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ImgHero, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(AttackB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastAH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scoreHero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addComponent(guion)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scoreVillain, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastAV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attack1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attack2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WinorLost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleVillain, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgVillain, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleHero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleVillain, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgVillain, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImgHero, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelVs)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreVillain, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreHero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastAV, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(lastAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AttackB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(PjSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(imgSpace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PjPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WinorLost, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgPower, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(attack1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attack2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PjSoul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgSoul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PjReal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgReal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgMind, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pjMind, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgTime, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pjTime, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(attack3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(attack4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(attack5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 48, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackBActionPerformed
        if(i>0 && i<6){double number = Math.random()*100;
        double numberV = Math.random()*100;
        int numberR =(int)number;
        int numberVi =(int)numberV;
        String value = String.valueOf(numberR);
        String valueV = String.valueOf(numberVi);
        scoreH +=numberR;
        scoreV +=numberVi;
        String pointH = String.valueOf(scoreH);
        String pointV = String.valueOf(scoreV);
        if(i==1){
            attack1.setText("ATTACK 1:   " + value);
            scoreHero.setText(pointH);
            PjPower.setText(valueV);
            double numberS = Math.random()*100;
            int numberSV =(int)numberS;
            String valueVS = String.valueOf(numberSV);
            PjSpace.setText(valueVS);
            scoreV += numberSV;
            String pointVs = String.valueOf(scoreV);
            scoreVillain.setText(pointVs);
        }
        if(i==2){
            attack2.setText("ATTACK 2:   " +value);
            scoreHero.setText(pointH);
            PjReal.setText(valueV);
            scoreVillain.setText(pointV);
            
        }
        if(i==3){
            attack3.setText("ATTACK 3:   " +value);
            scoreHero.setText(pointH);
            PjSoul.setText(valueV);
            scoreVillain.setText(pointV);
        }
        if(i==4){
            attack4.setText("ATTACK 4:   " +value);
            scoreHero.setText(pointH);
            pjTime.setText(valueV);
            scoreVillain.setText(pointV);
        }
        if(i==5){
            attack5.setText("ATTACK 5:   " +value);
            scoreHero.setText(pointH);
            pjMind.setText(valueV);
            scoreVillain.setText(pointV);
        }
        i++;
        if(i>5){
            if(scoreV>scoreH){
            WinorLost.setText("YOU LOSE");
            }
            if(scoreV<scoreH){
            WinorLost.setText("YOU WIN");    
            }
            if(scoreV==scoreH){
            WinorLost.setText("LAST ATTACK,press");  
            }
        }
        if(i>6&&scoreV==scoreH){
        double extra1 = Math.random()*50;
        int extraH =(int)extra1; 
        double extra2 = Math.random()*50;
        int extraV =(int)extra2; 
        String value1 = String.valueOf(extraH);
        String value2 = String.valueOf(extraV);
        lastAH.setText(value1);
        lastAV.setText(value2);
        scoreH += extraH;
        scoreV +=extraV;
        }
        }
    }//GEN-LAST:event_AttackBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(scoreH>scoreV&&i>5){
            IronManscreen screen = new  IronManscreen();
            screen.setVisible(true);
            this.setVisible(false);
        }
        if(scoreH<scoreV&&i>5){
            Villanscreen screen = new  Villanscreen();
            screen.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proof().setVisible(true);
            }
        });
    }
   public void changelabel(){
       String H = SHscreen.hero;
       String V = Vscreen.villain;
       if(H=="H1"){
          this.printImage(this.ImgHero, "src/main/java/Images/H1.jpg");
          titleHero.setText("IRON MAN");
       }
       if(H=="H2"){
          this.printImage(this.ImgHero, "src/main/java/Images/H2.jpg");
           titleHero.setText("CAPTAIN AMERICA");
       }
       if(H=="H3"){
          this.printImage(this.ImgHero, "src/main/java/Images/H3.jpg");
           titleHero.setText("THOR");
       }
       if(H=="H4"){
          this.printImage(this.ImgHero, "src/main/java/Images/H4.jpg");
           titleHero.setText("HULK");
       }
       if(H=="H5"){
          this.printImage(this.ImgHero, "src/main/java/Images/H5.jpg");
           titleHero.setText("SCARLET WITCH");
       }
       if(H=="H6"){
          this.printImage(this.ImgHero, "src/main/java/Images/H6.jpg");
           titleHero.setText("DOCTOR STRANGE");
       }
       if(H=="H7"){
          this.printImage(this.ImgHero, "src/main/java/Images/H7.jpg");
           titleHero.setText("CAPTAIN MARVEL");
       }
       if(V=="V1"){
          this.printImage(this.imgVillain, "src/main/java/Images/Ultron.png");
          titleVillain.setText("ULTRON");
       }
       if(V=="V2"){
          this.printImage(this.imgVillain, "src/main/java/Images/Thanos.jpg");
           titleVillain.setText("THANOS");
       }
   }
   public void printImage(JLabel lbs,String location){
       this.images =new ImageIcon(location);
       this.icons = new ImageIcon
       (this.images.getImage().getScaledInstance(
         lbs.getWidth(),
         lbs.getHeight(),
          Image.SCALE_DEFAULT)
       );
        lbs.setIcon(this.icons);
        this.repaint();        
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttackB;
    private javax.swing.JLabel ImgHero;
    private javax.swing.JLabel PjPower;
    private javax.swing.JLabel PjReal;
    private javax.swing.JLabel PjSoul;
    private javax.swing.JLabel PjSpace;
    private javax.swing.JLabel WinorLost;
    private javax.swing.JLabel attack1;
    private javax.swing.JLabel attack2;
    private javax.swing.JLabel attack3;
    private javax.swing.JLabel attack4;
    private javax.swing.JLabel attack5;
    private javax.swing.JLabel guion;
    private javax.swing.JLabel imgMind;
    private javax.swing.JLabel imgPower;
    private javax.swing.JLabel imgReal;
    private javax.swing.JLabel imgSoul;
    private javax.swing.JLabel imgSpace;
    private javax.swing.JLabel imgTime;
    private javax.swing.JLabel imgVillain;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelVs;
    private javax.swing.JLabel lastAH;
    private javax.swing.JLabel lastAV;
    private javax.swing.JLabel pjMind;
    private javax.swing.JLabel pjTime;
    private javax.swing.JLabel scoreHero;
    private javax.swing.JLabel scoreVillain;
    private javax.swing.JLabel titleHero;
    private javax.swing.JLabel titleVillain;
    // End of variables declaration//GEN-END:variables
}
