/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Marvel;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author georg
 */
public class SHscreen extends javax.swing.JFrame {
    public static String hero="";
    private ImageIcon images;
    private Icon icons;
    public SHscreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.printImage(this.imgIronMan, "src/main/java/Images/H1.jpg");
        this.printImage(this.imgCapAmerica, "src/main/java/Images/H2.jpg");
        this.printImage(this.imgThor, "src/main/java/Images/H3.jpg");
        this.printImage(this.imgHulk, "src/main/java/Images/H4.jpg");
        this.printImage(this.imgWitch, "src/main/java/Images/H5.jpg");
        this.printImage(this.imgDrStrange, "src/main/java/Images/H6.jpg");
        this.printImage(this.imgCapMarvel, "src/main/java/Images/H7.jpg");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        imgWitch = new javax.swing.JLabel();
        imgIronMan = new javax.swing.JLabel();
        imgCapAmerica = new javax.swing.JLabel();
        imgThor = new javax.swing.JLabel();
        H3Button = new javax.swing.JButton();
        H1Button = new javax.swing.JButton();
        H2Button = new javax.swing.JButton();
        H4Button = new javax.swing.JButton();
        imgHulk = new javax.swing.JLabel();
        imgCapMarvel = new javax.swing.JLabel();
        imgDrStrange = new javax.swing.JLabel();
        PLAYchose = new javax.swing.JButton();
        H5Button = new javax.swing.JButton();
        H6Button = new javax.swing.JButton();
        H7Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setPreferredSize(new java.awt.Dimension(600, 469));

        jPanel1.setPreferredSize(new java.awt.Dimension(596, 469));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(617, 453));

        imgWitch.setBackground(new java.awt.Color(255, 255, 255));
        imgWitch.setOpaque(true);

        imgIronMan.setBackground(new java.awt.Color(255, 255, 255));
        imgIronMan.setOpaque(true);

        imgCapAmerica.setBackground(new java.awt.Color(255, 255, 255));
        imgCapAmerica.setOpaque(true);

        imgThor.setBackground(new java.awt.Color(255, 255, 255));
        imgThor.setOpaque(true);

        H3Button.setBackground(new java.awt.Color(255, 255, 255));
        H3Button.setFont(new java.awt.Font("Burbank Big Condensed", 0, 18)); // NOI18N
        H3Button.setForeground(new java.awt.Color(204, 0, 0));
        H3Button.setText("SELECT");
        H3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H3ButtonActionPerformed(evt);
            }
        });

        H1Button.setBackground(new java.awt.Color(255, 255, 255));
        H1Button.setFont(new java.awt.Font("Burbank Big Condensed", 0, 18)); // NOI18N
        H1Button.setForeground(new java.awt.Color(204, 0, 0));
        H1Button.setText("SELECT");
        H1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1ButtonActionPerformed(evt);
            }
        });

        H2Button.setBackground(new java.awt.Color(255, 255, 255));
        H2Button.setFont(new java.awt.Font("Burbank Big Condensed", 0, 18)); // NOI18N
        H2Button.setForeground(new java.awt.Color(204, 0, 0));
        H2Button.setText("SELECT");
        H2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ButtonActionPerformed(evt);
            }
        });

        H4Button.setBackground(new java.awt.Color(255, 255, 255));
        H4Button.setFont(new java.awt.Font("Burbank Big Condensed", 0, 18)); // NOI18N
        H4Button.setForeground(new java.awt.Color(204, 0, 0));
        H4Button.setText("SELECT");
        H4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H4ButtonActionPerformed(evt);
            }
        });

        imgHulk.setBackground(new java.awt.Color(255, 255, 255));
        imgHulk.setOpaque(true);

        imgCapMarvel.setBackground(new java.awt.Color(255, 255, 255));
        imgCapMarvel.setOpaque(true);

        imgDrStrange.setBackground(new java.awt.Color(255, 255, 255));
        imgDrStrange.setOpaque(true);

        PLAYchose.setFont(new java.awt.Font("Burbank Big Condensed", 1, 24)); // NOI18N
        PLAYchose.setForeground(new java.awt.Color(204, 0, 0));
        PLAYchose.setText("NEXT");
        PLAYchose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYchoseActionPerformed(evt);
            }
        });

        H5Button.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        H5Button.setForeground(new java.awt.Color(204, 0, 0));
        H5Button.setText("SELECT");
        H5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H5ButtonActionPerformed(evt);
            }
        });

        H6Button.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        H6Button.setForeground(new java.awt.Color(204, 0, 0));
        H6Button.setText("SELECT");
        H6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H6ButtonActionPerformed(evt);
            }
        });

        H7Button.setFont(new java.awt.Font("Burbank Big Condensed", 1, 18)); // NOI18N
        H7Button.setForeground(new java.awt.Color(204, 0, 0));
        H7Button.setText("SELECT");
        H7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H7ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(H6Button)
                        .addGap(73, 73, 73)
                        .addComponent(H7Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(H1Button)
                        .addGap(73, 73, 73)
                        .addComponent(H2Button)
                        .addGap(73, 73, 73)
                        .addComponent(H3Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PLAYchose)
                        .addGap(51, 51, 51))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(H5Button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgIronMan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgWitch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgDrStrange, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgCapAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgThor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgCapMarvel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(H4Button))
                            .addComponent(imgHulk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgThor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCapAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgIronMan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgHulk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H3Button)
                    .addComponent(H1Button)
                    .addComponent(H2Button)
                    .addComponent(H4Button))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgWitch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgCapMarvel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgDrStrange, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(PLAYchose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H5Button)
                    .addComponent(H6Button)
                    .addComponent(H7Button))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void H7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H7ButtonActionPerformed
        H7Button.setBackground(Color.green);
        H1Button.setBackground(Color.white);
        H2Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        H4Button.setBackground(Color.white);
        H5Button.setBackground(Color.white);
        H6Button.setBackground(Color.white);
        hero="H7";
    }//GEN-LAST:event_H7ButtonActionPerformed

    private void H6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H6ButtonActionPerformed
        H6Button.setBackground(Color.green);
        H7Button.setBackground(Color.white);
        H1Button.setBackground(Color.white);
        H2Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        H4Button.setBackground(Color.white);
        H5Button.setBackground(Color.white);
        hero="H6";
    }//GEN-LAST:event_H6ButtonActionPerformed

    private void H5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H5ButtonActionPerformed
        H5Button.setBackground(Color.green);
        H6Button.setBackground(Color.white);
        H7Button.setBackground(Color.white);
        H1Button.setBackground(Color.white);
        H2Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        H4Button.setBackground(Color.white);
        hero="H5";
    }//GEN-LAST:event_H5ButtonActionPerformed

    private void PLAYchoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYchoseActionPerformed
        if(hero!=""){PLAYchose.setBackground(Color.green);
        Vscreen screen = new Vscreen();
        screen.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_PLAYchoseActionPerformed

    private void H4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H4ButtonActionPerformed
        H4Button.setBackground(Color.green);
        H5Button.setBackground(Color.white);
        H6Button.setBackground(Color.white);
        H7Button.setBackground(Color.white);
        H1Button.setBackground(Color.white);
        H2Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        hero="H4";
    }//GEN-LAST:event_H4ButtonActionPerformed

    private void H2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ButtonActionPerformed
        H2Button.setBackground(Color.green);
        H4Button.setBackground(Color.white);
        H5Button.setBackground(Color.white);
        H6Button.setBackground(Color.white);
        H7Button.setBackground(Color.white);
        H1Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        hero ="H2";
    }//GEN-LAST:event_H2ButtonActionPerformed

    private void H1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H1ButtonActionPerformed
        H1Button.setBackground(Color.green);
        H2Button.setBackground(Color.white);
        H4Button.setBackground(Color.white);
        H5Button.setBackground(Color.white);
        H6Button.setBackground(Color.white);
        H7Button.setBackground(Color.white);
        H3Button.setBackground(Color.white);
        hero = "H1";
    }//GEN-LAST:event_H1ButtonActionPerformed

    private void H3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H3ButtonActionPerformed
        H3Button.setBackground(Color.green);
        H1Button.setBackground(Color.white);
        H2Button.setBackground(Color.white);
        H4Button.setBackground(Color.white);
        H5Button.setBackground(Color.white);
        H6Button.setBackground(Color.white);
        H7Button.setBackground(Color.white);
        hero="H3";
    }//GEN-LAST:event_H3ButtonActionPerformed
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHscreen().setVisible(true);
            }
        });
    }

    private void printImage(JLabel lbs,String location){
        this.images = new ImageIcon(location);
        this.icons = new ImageIcon
        (this.images.getImage().getScaledInstance
                (lbs.getWidth(), 
                lbs.getHeight(),
                Image.SCALE_DEFAULT)
        );
        lbs.setIcon(this.icons);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton H1Button;
    private javax.swing.JButton H2Button;
    private javax.swing.JButton H3Button;
    private javax.swing.JButton H4Button;
    private javax.swing.JButton H5Button;
    private javax.swing.JButton H6Button;
    private javax.swing.JButton H7Button;
    private javax.swing.JButton PLAYchose;
    private javax.swing.JLabel imgCapAmerica;
    private javax.swing.JLabel imgCapMarvel;
    private javax.swing.JLabel imgDrStrange;
    private javax.swing.JLabel imgHulk;
    private javax.swing.JLabel imgIronMan;
    private javax.swing.JLabel imgThor;
    private javax.swing.JLabel imgWitch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
